name: ridesharing-sim
services:
  simulator-0:
    image: ridesharing_simulator:latest
    environment:
      NUM_RIDERS: 80
      NUM_DRIVERS: 100
      CITY: "San Francisco"
      KAFKA_BROKER: $KAFKA_BROKER
      KAFKA_SCHEMA_REGISTRY: $KAFKA_SCHEMA_REGISTRY
      KAFKA_SASL_USERNAME: $KAFKA_SASL_USERNAME
      KAFKA_SASL_PASSWORD: $KAFKA_SASL_PASSWORD

  simulator-1:
    image: ridesharing_simulator:latest
    environment:
      NUM_RIDERS: 50
      NUM_DRIVERS: 30
      CITY: "San Jose"
      KAFKA_BROKER: $KAFKA_BROKER
      KAFKA_SCHEMA_REGISTRY: $KAFKA_SCHEMA_REGISTRY
      KAFKA_SASL_USERNAME: $KAFKA_SASL_USERNAME
      KAFKA_SASL_PASSWORD: $KAFKA_SASL_PASSWORD